server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
#\u8FDE\u63A5\u914D\u7F6E\u4FE1\u606F
spring:
  application:
    name: m2e-sso-server